package stages

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/dencoseca/laptop-setup/internal/runner"
)

type FileSystem interface {
	MkdirAll(path string, perm fs.FileMode) error
	ReadFile(name string) ([]byte, error)
	WriteFile(name string, data []byte, perm fs.FileMode) error
	Stat(name string) (fs.FileInfo, error)
	AppendFile(name string, data []byte, perm fs.FileMode) error
}

type TemplateStore interface {
	LoadBrewEntries(name string) ([]BrewEntry, string, error)
	WriteGeneratedBrewfile(runDir string, sourcePath string, entries []BrewEntry) (string, error)
	Copy(name string, destination string) error
}

type PackageManager interface {
	HomebrewAvailable(context.Context) error
	RunBrewBundle(context.Context, ExecutionContext, string) error
}

type OSFileSystem struct{}

func (OSFileSystem) MkdirAll(path string, perm fs.FileMode) error {
	return os.MkdirAll(path, perm)
}

func (OSFileSystem) ReadFile(name string) ([]byte, error) {
	return os.ReadFile(name)
}

func (OSFileSystem) WriteFile(name string, data []byte, perm fs.FileMode) error {
	return os.WriteFile(name, data, perm)
}

func (OSFileSystem) Stat(name string) (fs.FileInfo, error) {
	return os.Stat(name)
}

func (OSFileSystem) AppendFile(name string, data []byte, perm fs.FileMode) error {
	file, err := os.OpenFile(name, os.O_CREATE|os.O_APPEND|os.O_WRONLY, perm)
	if err != nil {
		return err
	}
	defer file.Close()
	_, err = file.Write(data)
	return err
}

type FilesystemTemplateStore struct {
	RepoRoot string
	FS       FileSystem
}

func (s FilesystemTemplateStore) LoadBrewEntries(name string) ([]BrewEntry, string, error) {
	path, err := s.templatePath(name)
	if err != nil {
		return nil, "", err
	}
	content, err := s.fileSystem().ReadFile(path)
	if err != nil {
		return nil, "", fmt.Errorf("read Brewfile: %w", err)
	}
	return parseBrewEntries(string(content)), path, nil
}

func (s FilesystemTemplateStore) WriteGeneratedBrewfile(runDir string, sourcePath string, entries []BrewEntry) (string, error) {
	if strings.TrimSpace(runDir) == "" {
		return "", errors.New("run directory is required to generate Brewfile")
	}
	if len(entries) == 0 {
		return "", errors.New("generated Brewfile would be empty")
	}

	var builder strings.Builder
	builder.WriteString("# Generated by laptop-setup. Do not edit.\n")
	builder.WriteString(fmt.Sprintf("# Source: %s\n\n", sourcePath))
	for _, entry := range entries {
		builder.WriteString(entry.Line)
		builder.WriteString("\n")
	}

	fs := s.fileSystem()
	if err := fs.MkdirAll(runDir, 0o755); err != nil {
		return "", fmt.Errorf("create run directory: %w", err)
	}
	path := filepath.Join(runDir, "Brewfile.generated")
	if err := fs.WriteFile(path, []byte(builder.String()), 0o644); err != nil {
		return "", fmt.Errorf("write generated Brewfile: %w", err)
	}
	return path, nil
}

func (s FilesystemTemplateStore) Copy(name string, destination string) error {
	sourcePath, err := s.templatePath(name)
	if err != nil {
		return err
	}
	fs := s.fileSystem()
	if err := fs.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
		return fmt.Errorf("create destination directory: %w", err)
	}
	payload, err := fs.ReadFile(sourcePath)
	if err != nil {
		return fmt.Errorf("read source file: %w", err)
	}
	if err = fs.WriteFile(destination, payload, 0o644); err != nil {
		return fmt.Errorf("write destination file: %w", err)
	}
	return nil
}

func (s FilesystemTemplateStore) templatePath(name string) (string, error) {
	if strings.TrimSpace(s.RepoRoot) == "" {
		return "", errors.New("repository root is required")
	}
	return filepath.Join(s.RepoRoot, "templates", name), nil
}

func (s FilesystemTemplateStore) fileSystem() FileSystem {
	if s.FS != nil {
		return s.FS
	}
	return OSFileSystem{}
}

type HomebrewPackageManager struct {
	Runner runner.CommandRunner
}

func (m HomebrewPackageManager) HomebrewAvailable(ctx context.Context) error {
	if m.Runner == nil {
		return errors.New("runner is required")
	}
	if _, err := m.Runner.LookPath(ctx, "brew"); err != nil {
		return fmt.Errorf("brew executable not found: %w", err)
	}
	return nil
}

func (HomebrewPackageManager) RunBrewBundle(ctx context.Context, execCtx ExecutionContext, brewfilePath string) error {
	return runCommand(ctx, execCtx, runner.Command{
		Name: "brew",
		Args: []string{"bundle", "install", "--file", brewfilePath},
	})
}

func ResolveSelectedBrewIDsFromStore(store TemplateStore) ([]string, error) {
	if store == nil {
		return nil, errors.New("template store is required")
	}
	entries, _, err := store.LoadBrewEntries(defaultBrewTemplate)
	if err != nil {
		return nil, err
	}
	ids := make([]string, 0, len(entries))
	for _, entry := range entries {
		ids = append(ids, entry.ID)
	}
	return slices.Compact(ids), nil
}

func (execCtx ExecutionContext) fileSystem() FileSystem {
	if execCtx.FileSystem != nil {
		return execCtx.FileSystem
	}
	return OSFileSystem{}
}

func (execCtx ExecutionContext) templateStore() TemplateStore {
	if execCtx.TemplateStore != nil {
		return execCtx.TemplateStore
	}
	return FilesystemTemplateStore{
		RepoRoot: execCtx.RepoRoot,
		FS:       execCtx.fileSystem(),
	}
}

func (execCtx ExecutionContext) packageManager() PackageManager {
	if execCtx.PackageManager != nil {
		return execCtx.PackageManager
	}
	return HomebrewPackageManager{Runner: execCtx.Runner}
}
